apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: nodejs
          image: node:18-alpine
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "const http = require('http'); 
                    const hostname = '0.0.0.0'; 
                    const port = 3000; 
                    const server = http.createServer((req, res) => { 
                          res.statusCode = 200; 
                          res.setHeader('Content-Type', 'text/plain');
                          res.end('Hello World'); 
                        }); 
                        server.listen(port, hostname, () => { 
                          console.log('Server running at http://localhost:3000/'); 
                        });" > app.js
              node app.js
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: demo-svc
spec:
  selector:
    app: demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
